/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author HP
 */
public class L174031_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form L174031_Calculator
     */
    
    DecimalFormat format = new DecimalFormat("######.");
    Boolean symbolPressed = false; 
    Boolean CEPressed = false; 
    Boolean newEntry = false; 
    Boolean aa=false;
    Double num1 = 0.0;
    Double num2 = 0.0;
    Double result = 0.0;
    String op = "";
    int resultint=0;
    
    public L174031_Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton68 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton69 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton14.setText("jButton2");
        jButton14.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton15.setText("jButton2");
        jButton15.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton16.setText("jButton2");
        jButton16.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton17.setText("jButton2");
        jButton17.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton18.setText("jButton2");
        jButton18.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton19.setText("jButton2");
        jButton19.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton44.setText("jButton2");
        jButton44.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton45.setText("jButton2");
        jButton45.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton46.setText("jButton2");
        jButton46.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton47.setText("jButton2");
        jButton47.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton48.setText("jButton2");
        jButton48.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton49.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton49.setText("jButton2");
        jButton49.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton50.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton50.setText("jButton2");
        jButton50.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton51.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton51.setText("jButton2");
        jButton51.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton52.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton52.setText("jButton2");
        jButton52.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton53.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton53.setText("jButton2");
        jButton53.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton54.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton54.setText("jButton2");
        jButton54.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton55.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton55.setText("jButton2");
        jButton55.setPreferredSize(new java.awt.Dimension(100, 60));

        jLabel1.setText("jLabel1");

        jButton68.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton68.setText("jButton2");
        jButton68.setPreferredSize(new java.awt.Dimension(100, 60));

        jButton9.setBackground(new java.awt.Color(221, 223, 227));
        jButton9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jButton9.setText("x²");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton9.setContentAreaFilled(false);
        jButton9.setFocusPainted(false);
        jButton9.setFocusable(false);
        jButton9.setOpaque(true);
        jButton9.setPreferredSize(new java.awt.Dimension(100, 70));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(215, 217, 221));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 250));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(245, 247, 248));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("9");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setOpaque(true);
        jButton2.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        jButton3.setBackground(new java.awt.Color(232, 233, 236));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton3.setText(".");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setOpaque(true);
        jButton3.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, -1, -1));

        jButton4.setBackground(new java.awt.Color(245, 247, 248));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setText("3");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.setOpaque(true);
        jButton4.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jButton5.setBackground(new java.awt.Color(232, 233, 236));
        jButton5.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jButton5.setText("%");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.setOpaque(true);
        jButton5.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jButton6.setBackground(new java.awt.Color(245, 247, 248));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setText("6");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.setOpaque(true);
        jButton6.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        jButton7.setBackground(new java.awt.Color(232, 233, 236));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton7.setText("←");
        jButton7.setToolTipText("");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.setOpaque(true);
        jButton7.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jButton20.setBackground(new java.awt.Color(245, 247, 248));
        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton20.setText("7");
        jButton20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton20.setContentAreaFilled(false);
        jButton20.setFocusPainted(false);
        jButton20.setFocusable(false);
        jButton20.setOpaque(true);
        jButton20.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jButton21.setBackground(new java.awt.Color(232, 233, 236));
        jButton21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton21.setText("±");
        jButton21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton21.setContentAreaFilled(false);
        jButton21.setFocusPainted(false);
        jButton21.setFocusable(false);
        jButton21.setOpaque(true);
        jButton21.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, -1, -1));

        jButton22.setBackground(new java.awt.Color(245, 247, 248));
        jButton22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton22.setText("1");
        jButton22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton22.setContentAreaFilled(false);
        jButton22.setFocusPainted(false);
        jButton22.setFocusable(false);
        jButton22.setOpaque(true);
        jButton22.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        jButton24.setBackground(new java.awt.Color(245, 247, 248));
        jButton24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton24.setText("4");
        jButton24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton24.setContentAreaFilled(false);
        jButton24.setFocusPainted(false);
        jButton24.setFocusable(false);
        jButton24.setOpaque(true);
        jButton24.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        jButton25.setBackground(new java.awt.Color(232, 233, 236));
        jButton25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton25.setText("CE");
        jButton25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton25.setContentAreaFilled(false);
        jButton25.setFocusPainted(false);
        jButton25.setFocusable(false);
        jButton25.setOpaque(true);
        jButton25.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        jButton32.setBackground(new java.awt.Color(245, 247, 248));
        jButton32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton32.setText("8");
        jButton32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton32.setContentAreaFilled(false);
        jButton32.setFocusPainted(false);
        jButton32.setFocusable(false);
        jButton32.setOpaque(true);
        jButton32.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jButton33.setBackground(new java.awt.Color(245, 247, 248));
        jButton33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton33.setText("0");
        jButton33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton33.setContentAreaFilled(false);
        jButton33.setFocusPainted(false);
        jButton33.setFocusable(false);
        jButton33.setOpaque(true);
        jButton33.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        jButton34.setBackground(new java.awt.Color(245, 247, 248));
        jButton34.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton34.setText("2");
        jButton34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton34.setContentAreaFilled(false);
        jButton34.setFocusPainted(false);
        jButton34.setFocusable(false);
        jButton34.setOpaque(true);
        jButton34.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        jButton36.setBackground(new java.awt.Color(245, 247, 248));
        jButton36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton36.setText("5");
        jButton36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton36.setContentAreaFilled(false);
        jButton36.setFocusPainted(false);
        jButton36.setFocusable(false);
        jButton36.setOpaque(true);
        jButton36.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jButton37.setBackground(new java.awt.Color(232, 233, 236));
        jButton37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton37.setText("C");
        jButton37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton37.setContentAreaFilled(false);
        jButton37.setFocusPainted(false);
        jButton37.setFocusable(false);
        jButton37.setOpaque(true);
        jButton37.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jButton56.setBackground(new java.awt.Color(232, 233, 236));
        jButton56.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton56.setText("×");
        jButton56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton56.setContentAreaFilled(false);
        jButton56.setFocusPainted(false);
        jButton56.setFocusable(false);
        jButton56.setOpaque(true);
        jButton56.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jButton57.setBackground(new java.awt.Color(232, 233, 236));
        jButton57.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton57.setText("=");
        jButton57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton57.setContentAreaFilled(false);
        jButton57.setFocusPainted(false);
        jButton57.setFocusable(false);
        jButton57.setOpaque(true);
        jButton57.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton57ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        jButton58.setBackground(new java.awt.Color(232, 233, 236));
        jButton58.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton58.setText("_");
        jButton58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton58.setContentAreaFilled(false);
        jButton58.setFocusPainted(false);
        jButton58.setFocusable(false);
        jButton58.setOpaque(true);
        jButton58.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, -1));

        jButton60.setBackground(new java.awt.Color(232, 233, 236));
        jButton60.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton60.setText("+");
        jButton60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton60.setContentAreaFilled(false);
        jButton60.setFocusPainted(false);
        jButton60.setFocusable(false);
        jButton60.setOpaque(true);
        jButton60.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        jButton61.setBackground(new java.awt.Color(232, 233, 236));
        jButton61.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton61.setText("÷");
        jButton61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton61.setContentAreaFilled(false);
        jButton61.setFocusPainted(false);
        jButton61.setFocusable(false);
        jButton61.setOpaque(true);
        jButton61.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(214, 217, 223));
        jTextField1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 60)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.setBorder(null);
        jTextField1.setFocusable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 390, 110));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(214, 217, 223));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 390, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 26)); // NOI18N
        jLabel2.setText("≡   Standard");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jButton69.setBackground(new java.awt.Color(232, 233, 236));
        jButton69.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jButton69.setText("1 / x");
        jButton69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton69.setContentAreaFilled(false);
        jButton69.setFocusPainted(false);
        jButton69.setFocusable(false);
        jButton69.setOpaque(true);
        jButton69.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jButton8.setBackground(new java.awt.Color(232, 233, 236));
        jButton8.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jButton8.setText("x²");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusPainted(false);
        jButton8.setFocusable(false);
        jButton8.setOpaque(true);
        jButton8.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jButton10.setBackground(new java.awt.Color(232, 233, 236));
        jButton10.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jButton10.setText("√");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton10.setContentAreaFilled(false);
        jButton10.setFocusPainted(false);
        jButton10.setFocusable(false);
        jButton10.setOpaque(true);
        jButton10.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    void checkReulTreceived(){
        if(newEntry == true && CEPressed==false)
        {
            jTextField1.setText("0");
            jTextField2.setText("");
            newEntry = false;
        }
        num1=Double.parseDouble(jTextField1.getText());
    }
    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        checkReulTreceived();
        String s = jTextField1.getText();
        if(symbolPressed==true){
            jTextField1.setText("0"); 
            symbolPressed = false;
        }
        else{
            if(s.equals("0"))
            {
                jTextField1.setText("0"); 
            }
            else
                jTextField1.setText(s+"0");
        }
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        checkReulTreceived();
        String s = jTextField1.getText();
        if(symbolPressed==true){
            jTextField1.setText("2"); 
            symbolPressed = false;
        }
        else{
            if(s.equals("0"))
            {
                jTextField1.setText("2"); 
            }
            else
                jTextField1.setText(s+"2");
        }
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
if(symbolPressed == false){
            symbolPressed = true;
         
            if(newEntry==true || jTextField2.getText().equals("")){
                if(newEntry==true){
                    newEntry=false;
                }
                
                if(CEPressed==false){
                    num1 = Double.parseDouble(jTextField1.getText());
                    jTextField2.setText(jTextField1.getText()+"×");
                } 
                else{
                    CEPressed=false;
                    num1 = Double.parseDouble(jTextField2.getText());
                    jTextField2.setText(jTextField2.getText()+"×");
                    jTextField1.setText(num1.toString());
                }
            }
            else if(aa==true){
                aa=false;
                result = performOP();
                if(result % 1 == 0)
                result = 
                num1 = result;
                jTextField2.setText(result+"×"); 
                jTextField1.setText(result.toString()); 
            }
            else
            {
                num2 = Double.parseDouble(jTextField1.getText());
                String str = jTextField2.getText();
                op = str.substring(str.length() - 1);
                
                if(op.equals("+") || op.equals("×") || op.equals("×") || op.equals("÷")){
                    result = performOP();
                    if(CEPressed==false){
                    num1 = result;}
                    jTextField2.setText(result+"×"); 
                    jTextField1.setText(result.toString()); 
                }
                else{
                    if(CEPressed==true){
                        CEPressed=false;
                        jTextField1.setText(num1.toString());
                        jTextField2.setText(jTextField2.getText()+"×"); 
                    }
                    else
                        jTextField2.setText(num1+"×"); 
                }
            }
        }
        else{
            if(jTextField2.getText().equals("")){
                String str = jTextField1.getText();
                str = str.substring(0, str.length() - 1);
                jTextField2.setText(str+"×"); 
            }
            else
            {
                String str = jTextField2.getText();
                str = str.substring(0, str.length() - 1);
                jTextField2.setText(str+"×"); 
            }
        }


    }//GEN-LAST:event_jButton56ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        checkReulTreceived();
        String s = jTextField1.getText();
        if(symbolPressed==true){
            jTextField1.setText("1"); 
            symbolPressed = false;
        }
        else{
            if(s.equals("0"))
            {
                jTextField1.setText("1"); 
            }
            else
                jTextField1.setText(s+"1");
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        checkReulTreceived();
        String s = jTextField1.getText();
        if(symbolPressed==true){
            jTextField1.setText("3"); 
            symbolPressed = false;
        }
        else{
            if(s.equals("0"))
            {
                jTextField1.setText("3"); 
            }
            else
                jTextField1.setText(s+"3");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        checkReulTreceived();
        String s = jTextField1.getText();
        if(symbolPressed==true){
            jTextField1.setText("4"); 
            symbolPressed = false;
        }
        else{
            if(s.equals("0"))
            {
                jTextField1.setText("4"); 
            }
            else
                jTextField1.setText(s+"4");
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
        checkReulTreceived();
        String s = jTextField1.getText();
        if(symbolPressed==true){
            jTextField1.setText("5"); 
            symbolPressed = false;
        }
        else{
            if(s.equals("0"))
            {
                jTextField1.setText("5"); 
            }
            else
                jTextField1.setText(s+"5");
        }
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        checkReulTreceived();
        String s = jTextField1.getText();
        if(symbolPressed==true){
            jTextField1.setText("6"); 
            symbolPressed = false;
        }
        else{
            if(s.equals("0"))
            {
                jTextField1.setText("6"); 
            }
            else
                jTextField1.setText(s+"6");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        checkReulTreceived();
        String s = jTextField1.getText();
        if(symbolPressed==true){
            jTextField1.setText("7"); 
            symbolPressed = false;
        }
        else{
            if(s.equals("0"))
            {
                jTextField1.setText("7"); 
            }
            else
                jTextField1.setText(s+"7");
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
       checkReulTreceived();
       String s = jTextField1.getText();
        if(symbolPressed==true){
            jTextField1.setText("8"); 
            symbolPressed = false;
        }
        else{
            if(s.equals("0"))
            {
                jTextField1.setText("8"); 
            }
            else
                jTextField1.setText(s+"8");
        }
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        checkReulTreceived();
        String s = jTextField1.getText();
        if(symbolPressed==true){
            jTextField1.setText("9"); 
            symbolPressed = false;
        }
        else{
            if(s.equals("0"))
            {
                jTextField1.setText("9"); 
            }
            else
                jTextField1.setText(s+"9");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("0");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    public Double performOP(){
        if(op.equals("+"))
            result = num1+num2;
        if(op.equals("-"))
            result = num1-num2;
        if(op.equals("×"))
            result = num1*num2;
        if(op.equals("÷")){
            if(num2==0)
                jTextField1.setText("Can't divide by 0");
            else{
                result = num1/num2;
            }
        }
            result = Math.round(result * 10000.0) / 10000.0;
        return result;
    }
    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
if(symbolPressed == false){
            symbolPressed = true;
         
            if(newEntry==true || jTextField2.getText().equals("")){
                if(newEntry==true){
                    newEntry=false;
                }
                
                if(CEPressed==false){
                    num1 = Double.parseDouble(jTextField1.getText());
                    jTextField2.setText(jTextField1.getText()+"-");
                } 
                else{
                    CEPressed=false;
                    num1 = Double.parseDouble(jTextField2.getText());
                    jTextField2.setText(jTextField2.getText()+"-");
                    jTextField1.setText(num1.toString());
                }
            }
            else if(aa==true){
                aa=false;
                result = performOP();
                num1 = result;
                jTextField2.setText(result+"-"); 
                jTextField1.setText(result.toString()); 
            }
            else
            {
                num2 = Double.parseDouble(jTextField1.getText());
                String str = jTextField2.getText();
                op = str.substring(str.length() - 1);
                
                if(op.equals("+") || op.equals("-") || op.equals("×") || op.equals("÷")){
                    result = performOP();
                    if(CEPressed==false){
                    num1 = result;}
                    jTextField2.setText(result+"-"); 
                    jTextField1.setText(result.toString()); 
                }
                else{
                    if(CEPressed==true){
                        CEPressed=false;
                        jTextField1.setText(num1.toString());
                        jTextField2.setText(jTextField2.getText()+"-"); 
                    }
                    else
                        jTextField2.setText(num1+"-"); 
                }
            }
        }
        else{
            if(jTextField2.getText().equals("")){
                String str = jTextField1.getText();
                str = str.substring(0, str.length() - 1);
                jTextField2.setText(str+"-"); 
            }
            else
            {
                String str = jTextField2.getText();
                str = str.substring(0, str.length() - 1);
                jTextField2.setText(str+"-"); 
            }
        
        }    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        // TODO add your handling code here:        
        if(symbolPressed == false){
            symbolPressed = true;
         
            if(newEntry==true || jTextField2.getText().equals("")){
                if(newEntry==true){
                    newEntry=false;
                }
                
                if(CEPressed==false){
                    num1 = Double.parseDouble(jTextField1.getText());
                    if(num1 % 1 == 0){
                        resultint = (int) Math. round(num1);
                        jTextField2.setText(resultint+"+");
                    }
                    else
                        jTextField2.setText(num1+"+");
                } 
                else{
                    CEPressed=false;
                    
                    num1 = Double.parseDouble(jTextField2.getText());
                    if(num1 % 1 == 0){
                        resultint = (int) Math. round(num1);
                        jTextField2.setText(resultint+"+");
                    }
                    else
                        jTextField2.setText(num1+"+");
                    
                    jTextField1.setText(num1.toString());
                }
            }
            else if(aa==true){
                aa=false;
                result = performOP();
                num1 = result;
                if(num1 % 1 == 0){
                        resultint = (int) Math. round(num1);
                        jTextField2.setText(resultint+"+");
                        jTextField1.setText(resultint+""); 
                }
                else{
                    jTextField2.setText(result+"+"); 
                jTextField1.setText(result.toString()); }
            }
            else
            {
                num2 = Double.parseDouble(jTextField1.getText());
                String str = jTextField2.getText();
                op = str.substring(str.length() - 1);
                
                if(op.equals("+") || op.equals("-") || op.equals("×") || op.equals("÷")){
                    result = performOP();
                    if(CEPressed==false){
                    num1 = result;}
                    if(num1 % 1 == 0){
                        resultint = (int) Math. round(num1);
                        jTextField2.setText(resultint+"+");
                        jTextField1.setText(resultint+""); 
                }
                    else{
                    jTextField2.setText(result+"+"); 
                    jTextField1.setText(result.toString()); }
                }
                else{
                    if(CEPressed==true){
                        CEPressed=false;
                        if(num1 % 1 == 0){
                        resultint = (int) Math. round(num1);
                        jTextField2.setText(jTextField2.getText()+"+"); 
                        jTextField1.setText(resultint+""); 
                }else{
                        jTextField1.setText(num1.toString());
                        jTextField2.setText(jTextField2.getText()+"+"); }
                    }
                    else
                    {if(num1 % 1 == 0){
                        resultint = (int) Math. round(num1);
                        jTextField2.setText(resultint+"+"); 
                }
                    else
                        jTextField2.setText(num1+"+"); 
                    }
                }
            }
        }
        else{
            if(jTextField2.getText().equals("")){
                String str = jTextField1.getText();
                str = str.substring(0, str.length() - 1);
                jTextField2.setText(str+"+"); 
            }
            else
            {
                String str = jTextField2.getText();
                str = str.substring(0, str.length() - 1);
                jTextField2.setText(str+"+"); 
            }
        }
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        if(symbolPressed == false){
            symbolPressed = true;
         
            if(newEntry==true || jTextField2.getText().equals("")){
                if(newEntry==true){
                    newEntry=false;
                }
                
                if(CEPressed==false){
                    num1 = Double.parseDouble(jTextField1.getText());
                    jTextField2.setText(jTextField1.getText()+"÷");
                } 
                else{
                    CEPressed=false;
                    num1 = Double.parseDouble(jTextField2.getText());
                    jTextField2.setText(jTextField2.getText()+"÷");
                    jTextField1.setText(num1.toString());
                }
            }
            else if(aa==true){
                aa=false;
                result = performOP();
                if(num2==0){
                jTextField1.setText("Can't divide by 0");
                jTextField2.setText(num1+"/"+0);
                    }
                else{
                num1 = result;
                jTextField2.setText(result+"÷"); 
                jTextField1.setText(result.toString()); }            }
            else
            {
                num2 = Double.parseDouble(jTextField1.getText());
                String str = jTextField2.getText();
                op = str.substring(str.length() - 1);
                
                if(op.equals("+") || op.equals("÷") || op.equals("÷") || op.equals("÷")){
                result = performOP();
                    if(CEPressed==false){
                    num1 = result;}
                    if(num2==0){
                jTextField1.setText("Can't divide by 0");
                jTextField2.setText(num1+"/"+0);
                    }
                    else{
                    jTextField2.setText(result+"÷"); 
                    jTextField1.setText(result.toString()); 
                    }
                }
                else{
                    if(CEPressed==true){
                        CEPressed=false;
                        jTextField1.setText(num1.toString());
                        jTextField2.setText(jTextField2.getText()+"÷"); 
                    }
                    else
                        jTextField2.setText(num1+"÷"); 
                }
            }
        }
        else{
            if(jTextField2.getText().equals("")){
                String str = jTextField1.getText();
                str = str.substring(0, str.length() - 1);
                jTextField2.setText(str+"÷"); 
            }
            else
            {
                String str = jTextField2.getText();
                str = str.substring(0, str.length() - 1);
                jTextField2.setText(str+"÷"); 
            }
        }
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        String str = jTextField2.getText();
        op = str.substring(str.length() - 1);
        
        if(op.equals("+") || op.equals("-") || op.equals("×") || op.equals("÷")){
            str = str.substring(0, str.length() - 1);
            num1 = Double.parseDouble(str);
            CEPressed = true;
        }
        else{
            //num1= Double.parseDouble(str);
            //String split[] = str.split("(?<=\\d)(?=\\D)|(?<=\\D)(?=\\d)");
            //num1=Double.parseDouble(split[0]);
            //if("+".equals(split[1]) || "-".equals(split[1]) || "×".equals(split[1]) || "÷".equals(split[1])){
            //op=split[1];
            //num2=Double.parseDouble(split[2]);
            //result = performOP();
            //num1=result;
            //jTextField2.setText(result.toString());
            //jTextField1.setText("0");
            //}          
            //else 
            num1= Double.parseDouble(jTextField1.getText());
            jTextField2.setText(jTextField1.getText());
            CEPressed = true;
        }   
        jTextField1.setText("0");
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed
        // TODO add your handling code here:
        
        if(newEntry ==false && jTextField2.getText().equals(""))
        {
            num1 = Double.parseDouble(jTextField1.getText());
            jTextField2.setText(jTextField1.getText());
            newEntry = true;
        }
        else {
            if(newEntry ==false){
                
                num2 = Double.parseDouble(jTextField1.getText());
                String str = jTextField2.getText();
                op = str.substring(str.length() - 1);
                
                
                if(op.equals("+") || op.equals("-") || op.equals("×") || op.equals("÷")){
                    num1= Double.parseDouble(str.substring(0, str.length() - 1));
                    result = performOP();
                    System.out.println(num1+op+num2);
                    jTextField2.setText(num1+op+num2); 
                    jTextField1.setText(result.toString()); 
                    num1 = result;
                }
                else{
                    System.out.println(str);
                    String[] split = str.split("(?<=[\\d.])(?=[^\\d.])|(?<=[^\\d.])(?=[\\d.])");
                    num1=Double.parseDouble(split[0]);
                    op=split[1];
                    num2=Double.parseDouble(split[2]);
                    System.out.println(str);
                    System.out.println(num1+op+num2);
                    if("+".equals(split[1]) || "-".equals(split[1]) || "×".equals(split[1]) || "÷".equals(split[1])){
                        result = performOP();
                        num1=result;
                        jTextField2.setText(num1+op+num2); 
                        jTextField1.setText(result.toString()); 
                    }
                }
                symbolPressed=false;
                newEntry = true;
            }
        }
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());
        jTextField2.setText(1 + " / (" +jTextField1.getText()+")");
        if(num1==0)
            jTextField1.setText("Can't divide by 0");
        else
        {
            Double no = 1/num1;
            no = Math.round(no * 10000.0) / 10000.0;
            jTextField1.setText(no.toString());
            num1 = no;
        }
    }//GEN-LAST:event_jButton69ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String str = jTextField1.getText();
        if(!str.equals("")&&!str.isEmpty())
        {
            str = str.substring(0, str.length() - 1);
            if(str.length()==0){
                num1=0.0;
                str = "0";
            }
            jTextField1.setText(str);                
        }
        else
        {
            jTextField1.setText("0");
            num1=0.0;
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jTextField2.getText().equals("")){
            if(newEntry==true)
                newEntry=false;
            jTextField1.setText("0");
            jTextField2.setText("0");
        }

        else 
        {
            num2 = Double.parseDouble(jTextField1.getText());
            String str = jTextField2.getText();
            op = str.substring(str.length() - 1);
            str = str.substring(0, str.length() - 1);


            if(op.equals("+") || op.equals("-") || op.equals("×") || op.equals("÷")){
                num1=Double.parseDouble(str);
                result = num1*num2;
                result= result/100;
                num2 = result;
               
                jTextField1.setText(num2.toString());
                jTextField2.setText(num1 +op+ result);
                aa=true;
            }
            else{
                String[] split = str.split("(?<=[\\d.])(?=[^\\d.])|(?<=[^\\d.])(?=[\\d.])");
                
                num1=Double.parseDouble(split[0]);
                //op=split[1];
                //num2=Double.parseDouble(split[2]);
                result = num1*num2;
                result= result/100;
                num2 = result;
               
                jTextField1.setText(result.toString());
                jTextField2.setText(result.toString());
                aa=true;
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
        num1 = Double.parseDouble(jTextField1.getText());
        jTextField2.setText(" √ (" +jTextField1.getText()+")");
        if(num1<0)
            jTextField1.setText("Invalid Input");
        else
        {
            Double no = Math.sqrt(num1);
            no = Math.round(no * 10000.0) / 10000.0;
            jTextField1.setText(no.toString());
            num1 = no;
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String s = jTextField1.getText();
        if(symbolPressed==true){
            jTextField1.setText("."); 
            symbolPressed = false;
        }
        else{
            if(s.equals("0"))
            {
                jTextField1.setText("."); 
            }
            else
                jTextField1.setText(s+".");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        Double num = Double.parseDouble(jTextField1.getText());
        if(num != 0)
            num = num*-1;
        jTextField1.setText(num.toString());
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());
        jTextField2.setText("sqr (" +jTextField1.getText()+")");
        Double no = num1*num1;
        no = Math.round(no * 10000.0) / 10000.0;
        jTextField1.setText(no.toString());
        num1 = no;
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(L174031_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(L174031_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(L174031_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(L174031_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new L174031_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
